version: '3.8'

services:
  backend:
    build: ./todo-backend
    command: npm run dev
    volumes:
      - ./todo-backend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000

  frontend:
    build: ./todo-frontend
    command: npm start
    volumes:
      - ./todo-frontend:/app
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true